# Example deployment manifest for the TrustStack framework
version: v1

spec:
  awsOrganizationARN: "arn:aws:organizations::012345678901:organization/o-exampleorgid"

  awsOrganizationID: "o-exampleorgid"

  sharedServicesAccountID: "123456789012"

  securityPackages:
    # ECR Image Layer Access Security Package
    ecrImageLayerAccess:
      enabled: true
      configuration:
        allowedRoleNames:
          - TrustedRole
          - TrustedRole2
        allowedNetworks:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
        allowedVPCEndpoints:
          - vpce-0123456789abcdefg
          - vpce-0123456789abcdefh

    # Lambda Layer Permission Security Package
    lambdaLayerPermissionSecurity:
      enabled: true
      configuration:
        trustedAccountIDs:
          - "111122223333"
          - "444455556666"
        trustedOrgIDs:
          - "o-exampleorgid"

    # Lambda Permission Security Package
    lambdaPermissionSecurity:
      enabled: true
      configuration:
        trustedAccountIDs:
          - "111122223333"
          - "444455556666"
        trustedOrgIDs:
          - "o-exampleorgid"
        trustedServicePrincipals:
          - "s3.amazonaws.com"
          - "sns.amazonaws.com"
          - "events.amazonaws.com"

    # Lambda VPC Security Package
    lambdaVPCSecurity:
      enabled: true
      configuration:
        allowedVPCIDs:
          - vpc-0123456789abcdef0
          - vpc-0123456789abcdef1

    # SNS Subscription Security Package
    snsSubscriptionSecurity:
      enabled: true
      configuration:
        trustedEmailDomains:
          - example.com
          - trusted-domain.org
        trustedHTTPDomains:
          - api.example.com
          - webhook.trusted-domain.org
        trustedProtocols:
          - firehose
          - lambda
          - sqs
          - application
