packages:
  - apps/**
  - packages/**

onlyBuiltDependencies:
  - esbuild

catalog:
  "@aws-lambda-powertools/logger": "^2.17.0"
  "@aws-sdk/client-cloudformation": "3.758.0"
  "@aws-sdk/client-ec2": "3.758.0"
  "@aws-sdk/client-iam": "3.758.0"
  "@aws-sdk/client-lambda": "3.758.0"
  "@aws-sdk/client-securityhub": "3.758.0"
  "@aws-sdk/client-sns": "3.758.0"
  "@aws-sdk/client-ssm": "3.758.0"
  "@aws-sdk/client-sts": "3.758.0"
  "@aws-sdk/client-s3": "3.758.0"
  "@eslint/js": "^9.22.0"
  "@inquirer/prompts": "^7.4.0"
  "@jest/globals": "^29.7.0"
  "@middy/core": "^6.1.6"
  "@swc/core": "^1.11.8"
  "@swc/jest": "^0.2.37"
  "@types/aws-lambda": "^8.10.147"
  "@types/jest": "^29.5.14"
  "@types/js-yaml": "^4.0.9"
  "@types/node": "^22.13.10"
  "@types/yargs": "^17.0.33"
  "aws-cdk": "2.1003.0"
  "aws-cdk-lib": "2.182.0"
  "constructs": "^10.4.2"
  "dedent": "^1.5.3"
  "dotenv": "^16.4.7"
  "esbuild": "^0.25.1"
  "eslint": "^9.22.0"
  "eslint-plugin-n": "^17.16.2"
  "globals": "^16.0.0"
  "immer": "^10.1.1"
  "jest": "^29.7.0"
  "js-yaml": "^4.1.0"
  "prettier": "^3.5.3"
  "pretty-format": "^29.7.0"
  "ts-jest": "^29.3.4"
  "tsx": "^4.19.3"
  "typescript": "~5.8.2"
  "typescript-eslint": "^8.26.0"
  "yargs": "^17.7.2"
  "zod": "^3.24.2"
