version: "3"

tasks:
  format:
    desc: "Run code formatting(must specify Pants targets)"
    cmd: "pants fmt {{ .CLI_ARGS }}"

  "format:all":
    desc: "Format all the source files"
    cmd: "pants fmt ::"

  lint:
    desc: "Run linting(must specify Pants targets)"
    cmd: "pants lint {{ .CLI_ARGS }}"

  "lint:all":
    desc: "Lint all source files"
    cmd: "pants lint ::"
