version: "3"

tasks:
  lint:
    desc: "Lint the TrustStack engine code"
    dir: "apps/engine"
    cmd: pnpm lint

  format:
    desc: "Format the TrustStack engine code"
    dir: "apps/engine"
    cmd: pnpm format

  test:
    desc: "Test the TrustStack engine code"
    dir: "apps/engine"
    cmd: pnpm test

  "cdk:deploy":
    desc: "Deploy the TrustStack engine"
    dir: "apps/engine"
    cmd: pnpm cdk deploy {{ .CLI_ARGS }}

  "cdk:destroy":
    desc: "Remove the TrustStack engine from the environment"
    dir: "apps/engine"
    cmd: pnpm cdk destroy {{ .CLI_ARGS }}

  "cdk:diff":
    desc: "Present a diff of the TrustStack engine code against the deployed stacks"
    dir: "apps/engine"
    cmd: pnpm cdk diff {{ .CLI_ARGS }}

  "cdk:synth":
    desc: "Synthesize deployment artifacts for the TrustStack engine"
    dir: "apps/engine"
    cmd: pnpm cdk synth --version-reporting=false --path-metadata=false --asset-metadata=false --ci {{ .CLI_ARGS }}

  "cdk:ls":
    desc: "List the TrustStack engine stack"
    dir: "apps/engine"
    cmd: pnpm cdk ls
