version: "3"

tasks:
  "cdk:deploy":
    desc: "Deploy the TrustStack engine"
    dir: "apps/engine"
    cmds:
      - pnpm cdk deploy {{ .CLI_ARGS }}

  "cdk:destroy":
    desc: "Remove the TrustStack engine from the environment"
    dir: "apps/engine"
    cmds:
      - pnpm cdk destroy {{ .CLI_ARGS }}

  "cdk:diff":
    desc: "Present a diff of the TrustStack engine code against the deployed stack"
    dir: "apps/engine"
    cmds:
      - pnpm cdk diff {{ .CLI_ARGS }}

  "cdk:synth":
    desc: "Synthesize deployment artifacts for the TrustStack engine"
    dir: "apps/engine"
    cmds:
      - pnpm cdk synth --version-reporting=false --path-metadata=false --asset-metadata=false --ci {{ .CLI_ARGS }}

  package:
    desc: "Generate deployment artifacts for the TrustStack engine"
    dir: "apps/engine"
    cmds:
      - pnpm generate-deployment-assets

  upload-to-s3:
    desc: "Upload the generated deployment artifacts to the assets bucket"
    dir: "apps/engine"
    cmds:
      - rm -rf dist cdk.out
      - pnpm generate-deployment-assets
      - >
        ASSETS_BUCKET_NAME=$(aws ssm get-parameter --name "/trust-stack/assets-bucket/name" --query "Parameter.Value" --output text) &&
        aws s3 sync dist s3://$ASSETS_BUCKET_NAME/$BUILD_HASH/engine --delete
