version: "3"

env:
  DOCKER_CLI_TOOL: '{{ or .DOCKER_CLI_TOOL "docker" }}'

tasks:
  "docker:build":
    desc: "Build the Docker image"
    cmd: "{{ .DOCKER_CLI_TOOL }} build -t truststack-ci ."

  "docker:run":
    desc: "Run the Docker container"
    cmds:
      - rm -rf lza-config
      - mkdir lza-config
      - >
        {{ .DOCKER_CLI_TOOL }} run \
          -v ~/.aws:/root/.aws \
          -v ./.envrc:/app/.envrc \
          -v ./deployment-manifest.yml:/app/deployment-manifest.yml \
          -v ./lza-config:/app/lza-config \
          truststack-ci
