version: "3"

tasks:
  lint:
    desc: "Lint the TrustStack engine code"
    dir: "apps/engine"
    cmd: pnpm lint

  format:
    desc: "Format the TrustStack engine code"
    dir: "apps/engine"
    cmd: pnpm format

  test:
    desc: "Test the TrustStack engine code"
    dir: "apps/engine"
    cmd: pnpm test

  "cdk:deploy":
    desc: "Deploy the TrustStack engine"
    dir: "apps/engine"
    cmd: pnpm cdk deploy {{ .CLI_ARGS }}

  "cdk:destroy":
    desc: "Remove the TrustStack engine from the environment"
    dir: "apps/engine"
    cmd: pnpm cdk destroy {{ .CLI_ARGS }}

  "cdk:diff":
    desc: "Present a diff of the TrustStack engine code against the deployed stack"
    dir: "apps/engine"
    cmd: pnpm cdk diff {{ .CLI_ARGS }}

  "cdk:synth":
    desc: "Synthesize deployment artifacts for the TrustStack engine"
    dir: "apps/engine"
    cmd: pnpm cdk synth --version-reporting=false --path-metadata=false --asset-metadata=false --ci {{ .CLI_ARGS }}

  "cdk:ls":
    desc: "List the TrustStack engine stack"
    dir: "apps/engine"
    cmd: pnpm cdk ls

  package:
    desc: "Generate deployment artifacts for the TrustStack engine"
    dir: "apps/engine"
    cmd: pnpm generate-deployment-assets

  upload-to-s3:
    desc: "Upload the generated deployment artifacts to the assets bucket"
    dir: "apps/engine"
    cmds:
      - rm -rf dist cdk.out
      - pnpm generate-deployment-assets
      - >
        BUILD_HASH=$(task generate:build-hash) &&
        ASSETS_BUCKET_NAME=$(aws ssm get-parameter --name "/trust-stack/assets-bucket/name" --query "Parameter.Value" --output text) &&
        aws s3 sync dist s3://$ASSETS_BUCKET_NAME/$BUILD_HASH/engine --delete
