/**
 * TypeScript definitions for AWS::SecurityLake::DataLake
 * Generated from CloudFormation Resource Schema
 */

/**
 * Resource Type definition for AWS::SecurityLake::DataLake
 */
export namespace AWS_SecurityLake_DataLake {
  /**
   * Provides encryption details of Amazon Security Lake object.
   */
  export type EncryptionConfigurationType = {
    /**
     * The id of KMS encryption key used by Amazon Security Lake to encrypt the Security Lake object.
     */
    KmsKeyId?: string;
  };

  /**
   * Provides lifecycle details of Amazon Security Lake object.
   */
  export type LifecycleConfigurationType = {
    Expiration?: ExpirationType;

    /**
     * Provides data storage transition details of Amazon Security Lake object.
     */
    Transitions?: TransitionsType[];
  };

  /**
   * Provides data expiration details of Amazon Security Lake object.
   */
  export type ExpirationType = {
    Days?: DaysType;
  };

  /**
   * Number of days before data expires in the Amazon Security Lake object.
   */
  export type DaysType = {};

  export type TransitionsType = {
    /**
     * Number of days before data transitions to a different S3 Storage Class in the Amazon Security Lake object.
     */
    Days?: number;

    /**
     * The range of storage classes that you can choose from based on the data access, resiliency, and cost requirements of your workloads.
     */
    StorageClass?: string;
  };

  /**
   * Provides replication details of Amazon Security Lake object.
   */
  export type ReplicationConfigurationType = {
    Regions?: RegionsType;

    /**
     * Replication settings for the Amazon S3 buckets. This parameter uses the AWS Identity and Access Management (IAM) role you created that is managed by Security Lake, to ensure the replication setting is correct.
     */
    RoleArn?: string;
  };

  /**
   * Replication enables automatic, asynchronous copying of objects across Amazon S3 buckets. Amazon S3 buckets that are configured for object replication can be owned by the same AWS account or by different accounts. You can replicate objects to a single destination bucket or to multiple destination buckets. The destination buckets can be in different AWS Regions or within the same Region as the source bucket.
   */
  export type RegionsType = {};

  /**
   * A key-value pair to associate with a resource.
   */
  export type TagType = {
    /**
     * The key name of the tag. You can specify a value that is 1 to 128 Unicode characters in length and cannot be prefixed with aws:. You can use any of the following characters: the set of Unicode letters, digits, whitespace, `_`, `.`, `/`, `=`, `+`, and `-`.
     */
    Key: string;

    /**
     * The value for the tag. You can specify a value that is 0 to 256 characters in length.
     */
    Value: string;
  };

  /**
   * Resource Type definition for AWS::SecurityLake::DataLake
   */
  export type DataLakeResourceType = {
    EncryptionConfiguration?: EncryptionConfigurationType;

    LifecycleConfiguration?: LifecycleConfigurationType;

    ReplicationConfiguration?: ReplicationConfigurationType;

    /**
     * The Amazon Resource Name (ARN) used to index AWS Glue table partitions that are generated by the ingestion and normalization of AWS log sources and custom sources.
     */
    MetaStoreManagerRoleArn?: string;

    Tags?: TagType[];

    /**
     * The Amazon Resource Name (ARN) created by you to provide to the subscriber.
     * Read-only property
     */
    Arn?: string;

    /**
     * The ARN for the Amazon Security Lake Amazon S3 bucket.
     * Read-only property
     */
    S3BucketArn?: string;
  };
}
