/**
 * TypeScript definitions for AWS::EMR::Step
 * Generated from CloudFormation Resource Schema
 */

/**
 * Schema for AWS::EMR::Step
 */
export namespace AWS_EMR_Step {
  export type HadoopJarStepConfigType = {
    Args?: string[];

    Jar: string;

    MainClass?: string;

    StepProperties?: KeyValueType[];
  };

  export type KeyValueType = {
    Key?: string;

    Value?: string;
  };

  /**
   * Schema for AWS::EMR::Step
   */
  export type StepResourceType = {
    /**
     * ID generated by service
     * Read-only property
     */
    Id?: string;

    /**
     * This specifies what action to take when the cluster step fails. Possible values are CANCEL_AND_WAIT and CONTINUE.
     * Create-only property
     */
    ActionOnFailure: string;

    /**
     * The HadoopJarStepConfig property type specifies a job flow step consisting of a JAR file whose main function will be executed. The main function submits a job for the cluster to execute as a step on the master node, and then waits for the job to finish or fail before executing subsequent steps.
     * Create-only property
     */
    HadoopJarStep: HadoopJarStepConfigType;

    /**
     * A string that uniquely identifies the cluster (job flow).
     * Create-only property
     */
    JobFlowId: string;

    /**
     * The name of the cluster step.
     * Create-only property
     */
    Name: string;
  };
}
