/**
 * TypeScript definitions for AWS::EC2::VPCEndpointConnectionNotification
 * Generated from CloudFormation Resource Schema
 */

/**
 * Resource Type definition for AWS::EC2::VPCEndpointConnectionNotification
 */
export namespace AWS_EC2_VPCEndpointConnectionNotification {
  /**
   * Resource Type definition for AWS::EC2::VPCEndpointConnectionNotification
   */
  export type VPCEndpointConnectionNotificationResourceType = {
    /**
     * The endpoint events for which to receive notifications.
     */
    ConnectionEvents: string[];

    /**
     * The ID of the endpoint.
     * Create-only property
     */
    VPCEndpointId?: string;

    /**
     * VPC Endpoint Connection ID generated by service
     * Read-only property
     */
    VPCEndpointConnectionNotificationId?: string;

    /**
     * The ARN of the SNS topic for the notifications.
     */
    ConnectionNotificationArn: string;

    /**
     * The ID of the endpoint service.
     * Create-only property
     */
    ServiceId?: string;
  };
}
