/**
 * TypeScript definitions for AWS::AppSync::Api
 * Generated from CloudFormation Resource Schema
 */

/**
 * Resource schema for AppSync Api
 */
export namespace AWS_AppSync_Api {
  /**
   * The configuration for an Event Api
   */
  export type EventConfigType = {
    AuthProviders: AuthProvidersType;

    ConnectionAuthModes: AuthModesType;

    DefaultPublishAuthModes: AuthModesType;

    DefaultSubscribeAuthModes: AuthModesType;

    LogConfig?: EventLogConfigType;
  };

  /**
   * An auth mode.
   */
  export type AuthModeType = {
    AuthType?: AuthenticationTypeType;
  };

  /**
   * A list of auth modes for the AppSync API.
   */
  export type AuthModesType = {};

  /**
   * Security configuration for your AppSync API.
   */
  export type AuthenticationTypeType = {};

  /**
   * The OpenID Connect configuration.
   */
  export type OpenIDConnectConfigType = {
    ClientId?: string;

    AuthTTL?: number;

    Issuer: string;

    IatTTL?: number;
  };

  /**
   * Optional authorization configuration for using Amazon Cognito user pools with your API endpoint.
   */
  export type CognitoConfigType = {
    AppIdClientRegex?: string;

    UserPoolId: string;

    AwsRegion: string;
  };

  /**
   * A LambdaAuthorizerConfig holds configuration on how to authorize AWS AppSync API access when using the AWS_LAMBDA authorizer mode. Be aware that an AWS AppSync API may have only one Lambda authorizer configured at a time.
   */
  export type LambdaAuthorizerConfigType = {
    AuthorizerResultTtlInSeconds?: number;

    AuthorizerUri: string;

    IdentityValidationExpression?: string;
  };

  /**
   * A list of auth providers for the AppSync API.
   */
  export type AuthProvidersType = {};

  /**
   * An auth provider for the AppSync API.
   */
  export type AuthProviderType = {
    AuthType: AuthenticationTypeType;

    OpenIDConnectConfig?: OpenIDConnectConfigType;

    CognitoConfig?: CognitoConfigType;

    LambdaAuthorizerConfig?: LambdaAuthorizerConfigType;
  };

  /**
   * An arbitrary set of tags (key-value pairs) for this AppSync API.
   */
  export type TagType = {
    /**
     * A string used to identify this tag. You can specify a maximum of 128 characters for a tag key.
     */
    Key: string;

    /**
     * A string containing the value for this tag. You can specify a maximum of 256 characters for a tag value.
     */
    Value: string;
  };

  /**
   * An arbitrary set of tags (key-value pairs) for this AppSync API.
   */
  export type TagsType = {};

  /**
   * The name of the AppSync API.
   */
  export type ApiNameType = {};

  /**
   * The owner contact information for an API resource.
   */
  export type OwnerContactType = {};

  /**
   * A map of DNS names for the AppSync API.
   */
  export type DnsMapType = {
    Realtime?: string;

    Http?: string;
  };

  /**
   * Logging level for the AppSync API.
   */
  export type EventLogLevelType = {};

  /**
   * The log config for the AppSync API.
   */
  export type EventLogConfigType = {
    LogLevel: EventLogLevelType;

    CloudWatchLogsRoleArn: string;
  };

  /**
   * Resource schema for AppSync Api
   */
  export type ApiResourceType = {
    /**
     * The unique identifier for the AppSync Api generated by the service
     * Read-only property
     */
    ApiId?: string;

    /**
     * The Amazon Resource Name (ARN) of the AppSync Api
     * Read-only property
     */
    ApiArn?: string;

    Name: ApiNameType;

    OwnerContact?: OwnerContactType;

    /**
     * Read-only property
     */
    Dns?: DnsMapType;

    EventConfig?: EventConfigType;

    Tags?: TagsType;
  };
}
