/**
 * TypeScript definitions for AWS::Lambda::Alias
 * Generated from CloudFormation Resource Schema
 */

/**
 * Resource Type definition for AWS::Lambda::Alias
 */
export namespace AWS_Lambda_Alias {
  /**
   * A provisioned concurrency configuration for a function's alias.
   */
  export type ProvisionedConcurrencyConfigurationType = {
    /**
     * The amount of provisioned concurrency to allocate for the alias.
     */
    ProvisionedConcurrentExecutions: number;
  };

  /**
   * The traffic-shifting configuration of a Lambda function alias.
   */
  export type VersionWeightType = {
    /**
     * The percentage of traffic that the alias routes to the second version.
     */
    FunctionWeight: number;

    /**
     * The qualifier of the second version.
     */
    FunctionVersion: string;
  };

  /**
   * The traffic-shifting configuration of a Lambda function alias.
   */
  export type AliasRoutingConfigurationType = {
    /**
     * The second version, and the percentage of traffic that's routed to it.
     */
    AdditionalVersionWeights?: VersionWeightType[];
  };

  /**
   * Resource Type definition for AWS::Lambda::Alias
   */
  export type AliasResourceType = {
    /**
     * The name of the Lambda function.
     * Create-only property
     */
    FunctionName: string;

    /**
     * Lambda Alias ARN generated by the service.
     * Read-only property
     */
    AliasArn?: string;

    /**
     * Specifies a provisioned concurrency configuration for a function's alias.
     */
    ProvisionedConcurrencyConfig?: ProvisionedConcurrencyConfigurationType;

    /**
     * A description of the alias.
     */
    Description?: string;

    /**
     * The function version that the alias invokes.
     */
    FunctionVersion: string;

    /**
     * The routing configuration of the alias.
     */
    RoutingConfig?: AliasRoutingConfigurationType;

    /**
     * The name of the alias.
     * Create-only property
     */
    Name: string;
  };
}
