/**
 * TypeScript definitions for AWS::CloudFormation::ModuleVersion
 * Generated from CloudFormation Resource Schema
 */

/**
 * A module that has been registered in the CloudFormation registry.
 */
export namespace AWS_CloudFormation_ModuleVersion {
  /**
   * A module that has been registered in the CloudFormation registry.
   */
  export type ModuleVersionResourceType = {
    /**
     * The Amazon Resource Name (ARN) of the module.
     * Read-only property
     */
    Arn?: string;

    /**
     * The description of the registered module.
     * Read-only property
     */
    Description?: string;

    /**
     * The URL of a page providing detailed documentation for this module.
     * Read-only property
     */
    DocumentationUrl?: string;

    /**
     * The name of the module being registered.
     * Recommended module naming pattern: company_or_organization::service::type::MODULE.
     * Create-only property
     */
    ModuleName: string;

    /**
     * The url to the S3 bucket containing the schema and template fragment for the module you want to register.
     * Create-only property
     */
    ModulePackage: string;

    /**
     * Indicator of whether this module version is the current default version
     * Read-only property
     */
    IsDefaultVersion?: boolean;

    /**
     * The schema defining input parameters to and resources generated by the module.
     * Read-only property
     */
    Schema?: string;

    /**
     * The time that the specified module version was registered.
     * Read-only property
     */
    TimeCreated?: string;

    /**
     * The version ID of the module represented by this module instance.
     * Read-only property
     */
    VersionId?: string;

    /**
     * The scope at which the type is visible and usable in CloudFormation operations.
     * The only allowed value at present is:
     * PRIVATE: The type is only visible and usable within the account in which it is registered. Currently, AWS CloudFormation marks any types you register as PRIVATE.
     * Read-only property
     */
    Visibility?: string;
  };
}
