/**
 * TypeScript definitions for AWS::MemoryDB::MultiRegionCluster
 * Generated from CloudFormation Resource Schema
 */

/**
 * The AWS::MemoryDB::Multi Region Cluster resource creates an Amazon MemoryDB Multi Region Cluster.
 */
export namespace AWS_MemoryDB_MultiRegionCluster {
  /**
   * A key-value pair to associate with a resource.
   */
  export type TagType = {
    /**
     * The key for the tag. May not be null.
     */
    Key: string;

    /**
     * The tag's value. May be null.
     */
    Value: string;
  };

  /**
   * The AWS::MemoryDB::Multi Region Cluster resource creates an Amazon MemoryDB Multi Region Cluster.
   */
  export type MultiRegionClusterResourceType = {
    /**
     * The name of the Multi Region cluster. This value must be unique as it also serves as the multi region cluster identifier.
     * Create-only property
     */
    MultiRegionClusterNameSuffix?: string;

    /**
     * Description of the multi region cluster.
     */
    Description?: string;

    /**
     * The name of the Global Datastore, it is generated by MemoryDB adding a prefix to MultiRegionClusterNameSuffix.
     * Read-only property
     */
    MultiRegionClusterName?: string;

    /**
     * The status of the multi region cluster. For example, Available, Updating, Creating.
     * Read-only property
     */
    Status?: string;

    /**
     * The compute and memory capacity of the nodes in the multi region cluster.
     */
    NodeType: string;

    /**
     * The number of shards the multi region cluster will contain.
     */
    NumShards?: number;

    /**
     * The name of the parameter group associated with the multi region cluster.
     * Create-only property
     */
    MultiRegionParameterGroupName?: string;

    /**
     * A flag that enables in-transit encryption when set to true.
     * You cannot modify the value of TransitEncryptionEnabled after the cluster is created. To enable in-transit encryption on a cluster you must set TransitEncryptionEnabled to true when you create a cluster.
     * Create-only property
     */
    TLSEnabled?: boolean;

    /**
     * The Amazon Resource Name (ARN) of the multi region cluster.
     * Read-only property
     */
    ARN?: string;

    /**
     * The engine type used by the multi region cluster.
     */
    Engine?: string;

    /**
     * The Redis engine version used by the multi region cluster.
     * Create-only property
     */
    EngineVersion?: string;

    /**
     * An array of key-value pairs to apply to this multi region cluster.
     */
    Tags?: TagType[];

    /**
     * An enum string value that determines the update strategy for scaling. Possible values are 'COORDINATED' and 'UNCOORDINATED'. Default is 'COORDINATED'.
     */
    UpdateStrategy?: string;
  };
}
